"""update tokens

Revision ID: 9e26b8160159
Revises: 75d96299c530
Create Date: 2026-05-14 19:53:18.791073

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e26b8160159'
down_revision: Union[str, Sequence[str], None] = '75d96299c530'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tokens', sa.Column('refresh_token', sa.String(length=500), nullable=False))
    op.drop_column('tokens', 'verify_access_token')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tokens', sa.Column('verify_access_token', sa.VARCHAR(length=500), autoincrement=False, nullable=False))
    op.drop_column('tokens', 'refresh_token')
    # ### end Alembic commands ###
